### PR TITLE
Close Issue: Change backup folder structure

### PR DESCRIPTION
**Pull request by KeyboardNerd**
Simply replace '-' with '/' to make it work
Tested on OSX Yosemite with Sublime 3 Build 3126
e.g. now:
Backup saved to: ...sublime_backups/2016/09/27/...

### CODE REVIEW

**Comment by akalongman** [comment]
@KeyboardNerd is it working on Windows an Linux?

**Comment by ildarkhasanshin** [comment]
same https://github.com/akalongman/sublimetext-autobackups/pull/34/files ?

**Comment by KeyboardNerd** [comment]
Yes, Tested on Windows 10 and Linux Mint

**Comment by akalongman** [comment]
We need this feature as optional parameter in config

**Comment by KeyboardNerd** [comment]
understood, I'll send a new pull request once that's finished

**Pull request closed without merging**
