### PR TITLE
#28 - changed DATE/PATH to YEAR/MONTH/DAY/PATH for backup folder structure

### PR DESCRIPTION
**Pull request by dustinpho**

### CODE REVIEW

**Comment by akalongman** [comment]
Can you add this feature as optionally? Add new option in config `detailed_folders: true/false` (default false)

**Comment by ildarkhasanshin** [comment]
1 backups of the old structure /yyyy-mm-dd/time/path/ will work also?
2 as previously wrote perhaps even an option to implement /path/filename.ext.yyyymmddhhmmss ? so I think it's faster will display a list of backup files for a long period of time - i now have to leave for 1-2 minutes on the output file backups list (there are only about 5) for the last 2-3 months

**Comment by akalongman** [comment]
Yes, we dont want break plugin for all users :)

**Comment by KeyboardNerd** [comment]
This method will break "auto_backups_open_backup" function because the function uses regex for looking up the saving path. in function getData(self, time_folder)

**Comment by akalongman** [comment]
This PR is very old and not compatible with current package version

**Pull request closed without merging**
